### PR TITLE
jspm v0.17 compatibility

### PR DESCRIPTION
**Pull request by selfagency**
in re: #5

### CODE REVIEW

**Comment by DaSchTour** [comment]
Just to make sure it will work in different setups I'm wondering if sometime the ".js" extension is needed. While trying to migrate to jspm 0.17 I saw that karma-jspm has a "stripJSExtension" flag that can be set to false so that the "old" behavior still can be used.

**Comment by justinwilaby** [comment]
Do the unit tests pass with these changes on both 0.17 and 0.16?

**Comment by selfagency** [comment]
you can kill this PR if there's a better way of doing it. i've waited so long, i'm just using the cli now with grunt-exec.

**Comment by DaSchTour** [comment]
I was trying to get this working with jspm 0.17 and I guess it's easier to use the JSPM API directly

**Pull request closed without merging**
